# See config.example.yml for documentation.
object_base: orig/GOWE69
object: sys/main.dol
hash: 9619ba57c9919f95f7f2ac951a2166a3517f91e3
symbols: config/GOWE69/symbols.txt
splits: config/GOWE69/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
